#!/usr/bin/env ruby

current_pane = `tmux display-message -p "\#{pane_id}"`.strip
puts "Setting identifier for pane #{current_pane}"

system("tmux set-option -p -t #{current_pane} @is_aider 1")

model_value = ENV['AIDER_MODEL'] || 'sonnet'

reasoning_effort_value = ENV['AIDER_REASONING_EFFORT']
aider_command = [
  'aider',
  '--architect',
  '--dark-mode',
  '--model', model_value,
  '--no-analytics',
  '--no-auto-commit',
  '--no-gitignore',
  '--vim',
  '--watch-files'
]

if model_value =~ 'sonnet'
  aider_command << '--cache-prompts'
  aider_command << '--cache-keepalive-pings 2' # Keep cache alive for 15 min instead of the default 5 min
end

if File.exist?('.aider/CONVENTIONS.md')
  aider_command << '--read' << '.aider/CONVENTIONS.md'
end

if reasoning_effort_value
  aider_command << '--reasoning-effort' << reasoning_effort_value
end

aider_command = aider_command.join(' ')

puts "Running aider with options: #{aider_command}"

exec(aider_command)
