---

- name: Bootstrap ssh config
  template:
    backup: yes
    force: no
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    src: ssh/config
    mode: 0600
- name: Install XCode Command Line Tools
  command: xcode-select --install
  args:
    creates: /Library/Developer/CommandLineTools
- name: Setup log rotation
  template:
    backup: yes
    dest: /etc/newsyslog.d/projects.conf
    src: newsyslog/projects.conf
    owner: root
    mode: 0644
  become: true
- homebrew:
    name:  '{{ item }}'
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - ag
    - cmake
    - curl
    - dark-mode
    - fzf
    - git
    - ncdu
    - nmap
    - node
    - reattach-to-user-namespace
    - shellcheck
    - ssh-copy-id
    - tmux
    - vim
    - wget
- homebrew_cask:
    name: '{{ item }}'
  with_items:
    - firefox
    - google-backup-and-sync
    - google-chrome
    - intel-power-gadget
    - istat-menus
    - iterm2
    - kindle
    - lastpass
    - nvalt
    - sizeup
    - slack
- name: Install eslint
  npm:
    name: eslint
    global: yes
