---

- name: Bootstrap ssh config
  template:
    backup: yes
    force: no
    dest: '{{ ansible_env.HOME }}/.ssh/config'
    src: ssh/config
    mode: 0600
- name: Install XCode Command Line Tools
  command: xcode-select --install
  args:
    creates: /Library/Developer/CommandLineTools
- name: Use Cloudflare DNS
  command: networksetup -setdnsservers Wi-Fi 1.1.1.1 1.0.0.1
  changed_when: false
- name: Setup log rotation
  template:
    backup: yes
    dest: /etc/newsyslog.d/projects.conf
    src: newsyslog/projects.conf
    owner: root
    mode: 0644
  become: true
- homebrew:
    name:  '{{ item }}'
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - ag
    - cmake
    - curl
    - dark-mode
    - fzf
    - git
    - ncdu
    - nmap
    - node
    - reattach-to-user-namespace
    - shellcheck
    - ssh-copy-id
    - tmux
    - vim
    - wget
- homebrew_cask:
    name: '{{ item }}'
  with_items:
    - firefox
    - google-backup-and-sync
    - google-chrome
    - intel-power-gadget
    - istat-menus
    - iterm2
    - kindle
    - lastpass
    - nvalt
    - sizeup
    - slack
- name: Install eslint
  npm:
    name: eslint
    global: yes
- name: Clone vim config repository
  git:
    dest: '{{ ansible_env.HOME }}/.vim'
    repo: 'ssh://git@github.com/f1sherman/dotvim.git'
- name: Link .vimrc
  file:
    dest: '{{ ansible_env.HOME }}/.vimrc'
    src: '{{ ansible_env.HOME }}/.vim/vimrc'
    state: link
- name: Create .vimtmp directory
  file:
    path: '{{ ansible_env.HOME }}/.vimtmp'
    state: directory
- name: Initialize vim and install/update plugins
  command: '{{ item }}'
  changed_when: false
  with_items:
    - vim +qall
    - vim +PlugUpdate +qall
    - vim +PlugUpgrade +qall
    - vim +PlugClean +qall
- name: Check YouCompleteMe modification time
  stat:
    path: '{{ ansible_env.HOME }}/.vim/plugged/YouCompleteMe'
  register: youcompleteme
- name: Compile YouCompleteMe
  command: '{{ ansible_env.HOME }}/.vim/plugged/YouCompleteMe/install.py'
  when: ansible_date_time.epoch|float - youcompleteme.stat.mtime < 30 * 60
- name: Create projects directory
  file:
    path: '{{ ansible_env.HOME }}/projects'
    state: directory
- name: Clone dotfiles repository
  git:
    dest: '{{ ansible_env.HOME }}/projects/dotfiles'
    repo: 'ssh://git@github.com/f1sherman/dotfiles.git'
- name: Install dotfiles
  command: rake install
  args:
    chdir: '{{ ansible_env.HOME }}/projects/dotfiles'
    creates: '{{ ansible_env.HOME }}/.ackrc'
