---

- name: Setup log rotation
  template:
    backup: yes
    dest: /etc/newsyslog.d/projects.conf
    src: newsyslog/projects.conf
    owner: root
    mode: 0644
  become: true
- homebrew:
    name:  '{{ item }}'
  with_items:
    - ag
    - cmake
    - curl
    - dark-mode
    - fzf
    - git
    - htop
    - ncdu
    - nmap
    - node
    - reattach-to-user-namespace
    - shellcheck
    - ssh-copy-id
    - tmux
    - vim
    - wget
