# Initialize asdf for login shells. This is the last init script that is run
# after login.
if [[ -z "${ASDF_DIR}" ]]; then
  if command -v asdf > /dev/null; then source $(brew --prefix asdf)/asdf.sh; fi
fi
