# Don't require merge commit editing for conflict-free merges, see http://git-blame.blogspot.com/2012/02/updates-to-git-merge-in-upcoming-1710.html
export GIT_MERGE_AUTOEDIT=no

# Increase bash history
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}"

# Use UTF-8
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Enable colors in ls
export CLICOLOR='true'

# Use solorized colors in ls
export LSCOLORS='gxfxbEaEBxxEhEhBaDaCaD'

# Allow use of a ripgrep configuration file
export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

# Add to path avoiding duplicates
pathadd() {
  local newdir=${1%/}
  if [ -d "${1}" ] && ! echo "${PATH}" | grep --extended-regexp --quiet "(^|:)$newdir($|:)"; then
    PATH="${newdir}:${PATH}"
  fi
}

pathadd "${HOME}/bin"
pathadd "/usr/local/opt/curl-openssl/bin"

# Initialize nodenv and rbenv for non-login non-interactive shells. Otherwise it will be
# initialized in either zlogin or zshrc.
if [[ ! -o login && ! -o interactive ]]; then
  if command -v nodenv > /dev/null; then eval "$(nodenv init -)"; fi
  if command -v rbenv > /dev/null; then eval "$(rbenv init -)"; fi
fi
