# shellcheck shell=bash

if [[ -n "$ZSH_ENV_LOADED" ]]; then
  return 0  # Already loaded, skip rest of file
fi
export ZSH_ENV_LOADED=1

# Prepend to path avoiding duplicates
pathprepend() {
  local dir="${1%/}"
  if [ -d "${dir}" ]; then
    if [[ ":$PATH:" != *":${dir}:"* ]]; then
      PATH="${dir}:$PATH"
    else
      # Remove the directory from PATH
      PATH=":$PATH:"
      PATH=${PATH//:${dir}:/:}
      PATH=${PATH#:}
      PATH=${PATH%:}
      # Add it to the beginning
      PATH="${dir}:$PATH"
    fi
  fi
}

pathprepend "${HOME}/bin"
pathprepend "${HOME}/.local/bin"
if [[ "$OSTYPE" == "darwin"* ]]; then
  pathprepend "/opt/local/bin"
fi

# Homebrew support (works on macOS and Linuxbrew)
if command -v brew >/dev/null 2>&1; then
  : "${HOMEBREW_PREFIX:=$(brew --prefix 2>/dev/null)}"
  if [[ -n "${HOMEBREW_PREFIX}" ]]; then
    pathprepend "${HOMEBREW_PREFIX}/bin"
    pathprepend "${HOMEBREW_PREFIX}/opt/curl/bin"
    eval "$("${HOMEBREW_PREFIX}/bin/brew" shellenv)"
  fi
fi

# Load any machine-specific customizations
if [ -f ~/.zshenv.local ]; then
  # shellcheck disable=SC1090
  . ~/.zshenv.local
fi

# Don't require merge commit editing for conflict-free merges, see http://git-blame.blogspot.com/2012/02/updates-to-git-merge-in-upcoming-1710.html
export GIT_MERGE_AUTOEDIT=no

# Increase bash history
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}"

# Use UTF-8
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Enable colors in ls
export CLICOLOR='true'

# Use solorized colors in ls
export LSCOLORS='gxfxbEaEBxxEhEhBaDaCaD'

# Allow use of a ripgrep configuration file
export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

export PAGER='less -S'
export GH_PAGER='delta'

alias assume=". assume"

# Sets ANTHROPIC_API_KEY and OPENAI_API_KEY
for API_NAME in "openai" "anthropic"; do
  API_KEY_FILE="${HOME}/.config/api-keys/${API_NAME}"
  if [ -f "$API_KEY_FILE" ] && [ -s "$API_KEY_FILE" ]; then
    API_ENV_NAME="$(printf '%s' "$API_NAME" | tr '[:lower:]' '[:upper:]')_API_KEY"
    API_ENV_VALUE="$(<"$API_KEY_FILE")"
    export "${API_ENV_NAME}=${API_ENV_VALUE}"
  fi
done
