# shellcheck shell=bash

for zshenv_fragment in "${ZDOTDIR:-$HOME}"/.zshenv.d/*.zsh(N); do
  # shellcheck disable=SC1090
  source "$zshenv_fragment"
done
unset zshenv_fragment

if [ -f ~/.zshenv.local ]; then
  # shellcheck disable=SC1090
  . ~/.zshenv.local
fi
