# Don't require merge commit editing for conflict-free merges, see http://git-blame.blogspot.com/2012/02/updates-to-git-merge-in-upcoming-1710.html
export GIT_MERGE_AUTOEDIT=no

# Increase bash history
export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}"

# Use UTF-8
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Enable colors in ls
export CLICOLOR='true'

# Use solorized colors in ls
export LSCOLORS='gxfxbEaEBxxEhEhBaDaCaD'

# Allow use of a ripgrep configuration file
export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

export PAGER='less -S'

# Sets ANTHROPIC_API_KEY and OPENAI_API_KEY
for API_NAME in "openai" "anthropic"; do
  API_KEY_FILE="${HOME}/.config/api-keys/${API_NAME}"
  if [ -f "$API_KEY_FILE" ] && [ -s "$API_KEY_FILE" ]; then
    export "${API_NAME^^}_API_KEY"=$(<"$API_KEY_FILE")
  fi
done
