#!/usr/bin/env bash
set -euo pipefail

# Post a Showboat demo document as a comment on a Forgejo PR.
#
# Usage:
#   post-demo.sh [--image-url URL ...] <pr-number> <demo-file>
#
# Environment:
#   FORGEJO_TOKEN  - API token (default: read from ~/.config/home-network/forgejo-token)
#   FORGEJO_URL    - Base URL (default: https://forgejo.brianjohn.com)

FORGEJO_URL="${FORGEJO_URL:-https://forgejo.brianjohn.com}"
TOKEN_FILE="${HOME}/.config/home-network/forgejo-token"

image_urls=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image-url)
      image_urls+=("$2")
      shift 2
      ;;
    -h|--help)
      echo "Usage: post-demo.sh [--image-url URL ...] <pr-number> <demo-file>"
      exit 0
      ;;
    --)
      shift
      break
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      break
      ;;
  esac
done

if [[ $# -ne 2 ]]; then
  echo "Usage: post-demo.sh [--image-url URL ...] <pr-number> <demo-file>" >&2
  exit 1
fi

pr_number="$1"
demo_file="$2"

if [[ ! -f "$demo_file" ]]; then
  echo "Error: Demo file not found: ${demo_file}" >&2
  exit 1
fi

if [[ -n "${FORGEJO_TOKEN:-}" ]]; then
  token="$FORGEJO_TOKEN"
elif [[ -f "$TOKEN_FILE" ]]; then
  token="$(cat "$TOKEN_FILE")"
else
  echo "Error: No Forgejo token found. Set FORGEJO_TOKEN or create ${TOKEN_FILE}" >&2
  exit 1
fi

remote_url="$(git remote get-url origin 2>/dev/null || true)"
if [[ -z "$remote_url" ]]; then
  echo "Error: No 'origin' remote found" >&2
  exit 1
fi

repo_path="$(echo "$remote_url" | sed -E 's|.*[:/]([^/]+/[^/]+)$|\1|' | sed 's/\.git$//')"
owner="$(echo "$repo_path" | cut -d/ -f1)"
repo="$(echo "$repo_path" | cut -d/ -f2)"

comment_body_file="$(mktemp)"
trap 'rm -f "$comment_body_file"' EXIT

cat > "$comment_body_file" <<'HEADER'
## Live Proof (Showboat Demo)

This document was generated by [Showboat](https://github.com/simonw/showboat) to prove the changes work.

HEADER

if [[ "${#image_urls[@]}" -gt 0 ]]; then
  printf '## Screenshots\n\n' >> "$comment_body_file"
  for image_url in "${image_urls[@]}"; do
    printf '![Uploaded screenshot](%s)\n\n' "$image_url" >> "$comment_body_file"
  done
fi

cat >> "$comment_body_file" <<'MIDDLE'
<details>
<summary>Click to expand full demo output</summary>

MIDDLE

cat "$demo_file" >> "$comment_body_file"

cat >> "$comment_body_file" <<'FOOTER'

</details>
FOOTER

response="$(
  jq -n --rawfile body "$comment_body_file" '{body: $body}' | \
    curl -sf -X POST \
      -H "Authorization: token ${token}" \
      -H "Content-Type: application/json" \
      -d @- \
      "${FORGEJO_URL}/api/v1/repos/${owner}/${repo}/issues/${pr_number}/comments"
)"

comment_url="$(echo "$response" | jq -r '.html_url')"
echo "Posted demo comment: ${comment_url}"
