#!/usr/bin/env bash
set -euo pipefail

pr_number="${1:?usage: post-demo.sh \$PR_NUMBER \$DEMO_FILE}"
demo_file="${2:?usage: post-demo.sh \$PR_NUMBER \$DEMO_FILE}"

if [[ ! -f "$demo_file" ]]; then
  echo "Error: Demo file not found: ${demo_file}" >&2
  exit 1
fi

repo="$(gh repo view --json nameWithOwner --jq '.nameWithOwner')"
comment_file="$(mktemp)"
trap 'rm -f "$comment_file"' EXIT

cat >"$comment_file" <<'HEADER'
## Live Proof (Showboat Demo)

This document was generated by [Showboat](https://github.com/simonw/showboat) to prove the changes work.

<details>
<summary>Click to expand full demo output</summary>

HEADER

cat "$demo_file" >>"$comment_file"
printf '\n</details>\n' >>"$comment_file"

gh pr comment "$pr_number" --repo "$repo" --body-file "$comment_file"
